"""Subset Noto Sans SC/KR variable fonts to the glyphs VokalBoard needs (wght 400-700)."""
import json, os, sys
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools import subset

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Usage: python scripts/subset_cjk_fonts.py <dir with NotoSansSC-VF.otf + NotoSansKR-VF.otf>
#   (from github.com/notofonts/noto-cjk, Sans/Variable/OTF/Subset/). Needs: pip install fonttools brotli
SRC = sys.argv[1]
OUT = os.path.join(REPO, "app", "static", "fonts", "noto-cjk")
os.makedirs(OUT, exist_ok=True)


def json_chars(lang):
    with open(os.path.join(REPO, "app", "locales", f"{lang}.json"), encoding="utf-8") as f:
        return set("".join(v for v in json.load(f).values() if isinstance(v, str)))


def codec_block(codec, lead_lo, lead_hi):
    out = set()
    for a in range(lead_lo, lead_hi + 1):
        for b in range(0xA1, 0xFF):
            try:
                out.add(bytes([a, b]).decode(codec))
            except UnicodeDecodeError:
                pass
    return out


PUNCT = {chr(c) for c in list(range(0x3000, 0x3040)) + list(range(0xFF00, 0xFFF0))}

# zh: GB2312 level 1 (3755 most common hanzi) + everything in zh.json
zh = codec_block("gb2312", 0xB0, 0xD7) | json_chars("zh") | PUNCT
# ko: KS X 1001 Hangul (2350 common syllables) + compatibility jamo + ko.json
ko = codec_block("euc_kr", 0xB0, 0xC8) | {chr(c) for c in range(0x3131, 0x318F)} | json_chars("ko") | PUNCT


def ranges(cps):
    cps=sorted(cps); out=[]; lo=prev=cps[0]
    for c in cps[1:]+[None]:
        if c is not None and c==prev+1: prev=c; continue
        out.append(f"U+{lo:X}" if lo==prev else f"U+{lo:X}-{prev:X}")
        if c is not None: lo=prev=c
    return ", ".join(out)

# Two files per language: "ui" (chars in the locale file) and "common" (the rest); unicode-range
# makes browsers fetch "common" only when a page actually contains one of its chars.
css=[]
for name, lang, chars in (("NotoSansSC","zh",zh),("NotoSansKR","ko",ko)):
    ui = {ord(c) for c in json_chars(lang) | PUNCT if ord(c) >= 0x2E80}
    common = {ord(c) for c in chars if ord(c) >= 0x2E80} - ui
    for part, cps in (("ui", ui), ("common", common)):
        font = TTFont(os.path.join(SRC, f"{name}-VF.otf"))
        font = instancer.instantiateVariableFont(font, {"wght": (400, 700)})
        opts = subset.Options(); opts.flavor="woff2"; opts.layout_features=["*"]; opts.name_IDs=["*"]; opts.notdef_outline=True
        sub = subset.Subsetter(opts); sub.populate(unicodes=cps); sub.subset(font)
        font.flavor="woff2"
        fn=f"{name.lower()}-{part}-400-700.woff2"; font.save(os.path.join(OUT, fn))
        print(f"{fn}: {len(cps)} chars -> {os.path.getsize(os.path.join(OUT, fn))//1024} KB")
        fam = "Noto Sans SC" if lang=="zh" else "Noto Sans KR"
        css.append(f"@font-face {{ font-family:'{fam}'; font-style:normal; font-weight:400 700; font-display:swap; src:url('/static/fonts/noto-cjk/{fn}') format('woff2'); unicode-range:{ranges(cps)}; }}")
HEADER = '/* Self-hosted Noto Sans SC/KR subsets (SIL OFL 1.1, app/static/fonts/noto-cjk/). Loaded by base.html only for lang zh/ko.\n   Generated by scripts/subset_cjk_fonts.py — do not edit by hand. "ui" = chars used in the locale file (always needed);\n   "common" = remaining common hanzi/hangul, fetched only when a page contains one (unicode-range). */'
with open(os.path.join(REPO, "app", "static", "css", "fonts-cjk.css"), "w", encoding="utf-8") as f:
    f.write(HEADER + "\n" + "\n".join(css) + "\n")
